### ISSUE TITLE
Compare current validation schema against specs

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#117]
I'd like to go through the schema soon and check this against the specs to verify that the validations are complete.

**Comment by juliangruber** [comment]
For each not matching validation (if there is one) it would be great to also add a regression test

**Comment by jameslibscie** [comment]
This ended up being a bit more complicated than I expected. @dpaez, there are quite a few things I'm not sure of, so please correct me if I'm wrong.

There are multiple ways in which the module metadata is validated, each of which take care of a piece of the specs:
- Validation on DB schema via `[content/profile].json` files
- Validation on DB schema via `validate.js`
- Validation on `init()`
- Validation on `set()`
- Validation on special action, like `publish()`

I think we will eventually need a single `validate()` method that checks the current state of the metadata and does a complete check, returning warnings for breaking `SHOULDs` and errors for breaking `MUSTs`. For example, if people are manually editing the metadata or using something other than the SDK, this ensures correctness. But perhaps the main advantage for us for now is that it creates an easy overview of validations, which is useful in times where the specs are still changing. I also think it would be much easier to match the test coverage to the validations if the validations are laid out.

Other than that, if we presume that the SDK is the only one editing the metadata, then there are a few mostly minor findings:
- The SDK doesn't seem to enforce that `links.license` refers to the CC0 URL
- The SDK doesn't seem to enforce that `links.spec` refers to the version of the specs that the SDK uses (for example by updating it?). What currently sets the spec version? Maybe I missed some code...
- `p2pcommons.subtype` has no validation
- `p2pcommons.avatar` seems to be mandatory (?), even though it is allowed to not exist
- The uniqueness definitions from specs `v0.2.4` don't seem to be implemented yet (`authors`, `parents`, `follows`, `contents`) (but the no-whitespace-`title` spec from `v0.2.5` already does seem to be implemented?)
- There doesn't seem to be a check that the `p2pcommons.authors` are non-versioned, except for the reference to the current user's profile
- There doesn't seem to be a check that `p2pcommons.parents` are versioned, except for when they self-reference (not sure about this)
- The test coverage seems to cover mostly the bugs that have been found, rather than a complete coverage of the specs

Some things that we might actually want to adjust in the specs rather than the SDK
- The SDK requires `dat://` in the `url`, which is technically correct according to the definition of `url`, but is currently optional in the specs. This will be solved by [specs/#30](https://github.com/p2pcommons/specs/pull/30)

And also some findings in the specs:
- The regex for `p2pcommons.subtype` doesn't allow for an empty string, but `subtype` is allowed to be empty
- For `p2pcommons.main`: "The relative path SHOULD refer to a valid relative file within the Dat archive". What is a _relative file_? Should this not just be file?
- Do we want to define what an image file is for `p2pcommons.avatar`?

So here's an idea for a plan of action:
- When specs `v0.2.6` is accepted, the task of bringing the SDK up to spec includes creating a validation method that does a complete validation of the metadata. I can help to spec this as I have quite a good overview now of what validations are necessary and can write error messages per validation. In doing so, most of the current validations can probably drop away?
- Then, test cases are added to (regression) test each validation rule
- I send the specs findings to the p2pcommons working group

@dpaez @juliangruber What do you think?

**Comment by juliangruber** [comment]
> * "The relative path SHOULD refer to a valid relative file within the Dat archive". What is a _relative file_? Should this not just be file?

Rather than _relative file_ this should be _relative file path_.

> * Do we want to define what an image file is for `p2pcommons.avatar`?

This has been discussed in the specs repo (or somewhere around it) and we decided not to limit this for now.

I'll leave to @dpaez to talk about the actual implementation, but getting this to match the spec, with test coverage, would be awesome.

**Comment by chartgerink** [comment]
Expanding a bit for @jameslibscie on the why for the relative file path: We don't want people to hardcode absolute file paths into (e.g., `/home/chris/.p2pcommons/<key>/test.txt`) because it's not robust across devices.

**Comment by dpaez** [comment]
Good write-up @jameslibscie. I think the SDK followed the spec updates until version 0.2.4 and 0.2.5 and .6 remain to be implemented. I think also that the specs are now entering into a more formal or solid state than what they were before. So I understand this gap to be something that it could happen. 

We have some schemas, those help us to _formalize_ what are we storing. This also give us some base validations. But these schemas can't grasp all the more detailed or top level validations that arise from the spec, things like what happen when a user publish something.
Also at the beginning it wasn't  💯clear from where a change can come from. `init` and `set` for example. We try to remediate some of this and now we have this validate function which tries to centralize validations methods.

I like to think about this idea of having this like CLI mechanism for validate metadata. But I also found when I'm working with validations that it is important to know the action that the user is trying to do. So there is a relation between both. It's like an action triggers validation. This adds complexity.

I like the plan of action. 👍

**Comment by jameslibscie** [comment]
@dpaez: Great, so if I understand correctly, we should then expand this central validation function to encompass all validations. In cases where the validation is action dependent, like the `main` file which may be empty upon `init` or `set`, but not upon `publish`, they will need to be either conditional or split off into a more specific validation function for certain contexts (which I think you already have now to a certain extent). Shall I create an issue that outlines this?

@juliangruber @chartgerink: The suggestion wasn't to remove the reference to "relative" altogether, but the mention of a relative path AND a relative file seems superfluous to me. It might help to have the complete spec here:
> `p2pcommons.main` MUST be a string containing one relative path but MUST NOT refer to a relative home or relative parent directory. The relative path SHOULD refer to a valid relative file within the Dat archive (see also Registration). The `./` part of a relative path MAY be included.
It's clear to me that the path has to be relative and I don't see how changing "valid relative file" to "valid file" opens up any new possibilities.

**Comment by dpaez** [comment]
@jameslibscie yeah, I think that we can start from there 👍

**Comment by chartgerink** [comment]
> @juliangruber @chartgerink: The suggestion wasn't to remove the reference to "relative" altogether, but the mention of a relative path AND a relative file seems superfluous to me. It might help to have the complete spec here:
> 
> > `p2pcommons.main` MUST be a string containing one relative path but MUST NOT refer to a relative home or relative parent directory. The relative path SHOULD refer to a valid relative file within the Dat archive (see also Registration). The `./` part of a relative path MAY be included.
> 
> It's clear to me that the path has to be relative and I don't see how changing "valid relative file" to "valid file" opens up any new possibilities.

This seems like a pebble issue that can be discussed in specs if we want.

**Comment by jameslibscie** [comment]
Issue created #154 
Specs issues tacked in [specs/#32](https://github.com/p2pcommons/specs/pull/32)
