### ISSUE TITLE
Set profile avatar

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#118]
**Acceptance criteria**
- [ ] The profile avatar can be set via the `set()` method

**[`p2pcommons/specs`](https://github.com/p2pcommons/specs/blob/master/module.md#keyvalues)**
If included, p2pcommons.avatar MUST be a string containing one relative path that MUST NOT refer to a relative home or relative parent directory. The relative path SHOULD refer to a valid image file within the Dat archive (see also Registration). The ./ part of a relative path MAY be included.

**Background**
I think when we spoke about this @dpaez, you said that the schema was missing a spot for the avatar? Either way, we thought that this wouldn't currently work.

**Comment by juliangruber** [comment]
@jameslibscie should this also make it into the CLI?

**Comment by jameslibscie** [comment]
@juliangruber Yes. It's further down the line on the Hypergraph roadmap, though, which is why there's isn't an issue for it yet. If you have time spare, let me know and I can create some CLI issues to let the CLI catch up to SDK (and run ahead of Desktop).
