### ISSUE TITLE
Connect Daemon to swarm

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#123]
*Waiting for #122* ❗️ 

**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [ ] There is an application separate from the SDK that can connect to the swarm and synchronise while the application is running

**Comment by juliangruber** [comment]
This is implemented in the daemon already and doesn't need to be done on our side
