### ISSUE TITLE
Daemon always on

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#124]
*Waiting for #122* ❗️ 

**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [ ] The Daemon can stay alive for extended periods of time
- [ ] The Daemon can installed with the option to launch upon OS startup
- [ ] CPU, memory usage and network traffic of the Daemon is measured and reported (needs scenarios ❗️ )

**Comment by juliangruber** [comment]
> * Performance of the Daemon is measured and reported (needs scenarios ❗️ )

What do you mean by performance? Network traffic, or cpu / memory usage?

**Comment by juliangruber** [comment]
All of these are also part of the electron app too

**Comment by jameslibscie** [comment]
Replaced by [hypergraph-xyz/hyperdrive-daemon-app/#2](https://github.com/hypergraph-xyz/hyperdrive-daemon-app/issues/2)
