### ISSUE TITLE
Connect Daemon to SDK

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#125]
*Waiting for #122* ❗️ 

**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [ ] The SDK can connect to the Daemon (for what?)

**Comment by juliangruber** [comment]
The SDK needs to tell the daemon which modules to sync, and the daemon needs to tell the SDK status updates. I think those are the main interactions?
