### ISSUE TITLE
View Daemon status

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#126]
*Waiting for #122* ❗️ 

**User story**
As a content creator
I want my profile and content to continuously synchronize to the network
so that my work is more available and more quickly updated

**Acceptance criteria**
- [ ] While the Daemon is running, a system tray icon is displayed
- [ ] The system tray icons allows the user to close the Daemon
- [ ] Hovering over the system tray icon displays whether the Daemon is running correctly or not

**Comment by juliangruber** [comment]
> * Hovering over the system tray icon displays whether the Daemon is running correctly or not

This is also commonly achieved using a menu that shows when you click the icon, a la

![locating-dropbox-icon](https://user-images.githubusercontent.com/10247/76499001-3816f500-643e-11ea-8393-267aeb9b1242.jpg)

We can definitely start with a tooltip though, this should work on every os too.

**Comment by jameslibscie** [comment]
Absolutely. Start minimal and progress from there :)

**Comment by juliangruber** [comment]
> * While the Daemon is running, a system tray icon is displayed

This won't be part of the SDK, but of the electron app

**Comment by jameslibscie** [comment]
Replaced by [hypergraph-xyz/hyperdrive-daemon-app/#3](https://github.com/hypergraph-xyz/hyperdrive-daemon-app/issues/3)
