### ISSUE TITLE
.clone() output inconsistent with other methods

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#129]
I understand the `clone()` method used to be internal, but now that it's exposed and documented, it would be nice if its output would match that of other methods, like `get()`.

I currently do this conversion manually:

```js
const modules = cloned.map(c => ({
  rawJSON: {
    title: c.module.title,
    description: c.module.description,
    url: c.module.url,
    type: c.module.p2pcommons.type,
    subtype: c.module.p2pcommons.subtype,
    main: c.module.p2pcommons.main,
    authors: c.module.p2pcommons.authors,
    parents: c.module.p2pcommons.parents
  },
  metadata: c.metadata
}))
```

**Comment by dpaez** [comment]
oh this is nasty, let's fix it

**Comment by juliangruber** [comment]
I'm reopening this because it's still `mod.module` instead of `mod.rawJSON`. All the other properties match though :)

**Comment by dpaez** [comment]
on it 😅
