### ISSUE TITLE
Get date modified for locally created / owned modules

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#138]
**User story**
As a content creator
I want to be able to see my last modified modules first
so that I can get to the content I'm currently working on more quickly

**Acceptance criteria**
- [ ] There is a way to get a date modified for content modules
- [ ] This only works for content modules that you own
- [ ] There is a way to get a list of owned content modules that includes a date modified (so that the implementation can easily sort) OR a way to get a date modified (new-old) sorted list of owned content modules

**Comment by juliangruber** [comment]
As far as I understand, we can tell when my local modules were last modified (if the system clock is correct), however we can't say so of remote content. With remote content we can keep track of when we first saw it, but I think that belongs into the apps instead.

**Comment by jameslibscie** [comment]
Remote modules won't appear on the workspace anyway until we have collaboration features (and then we can use the "appeared" date). We can also use the "appeared" date for other remote content, but we'll get to that later when we have a feed. And we indeed don't have remote modules yet, but I think it's nice to spec this out already, since we've already agreed that "date modified" is a concept we only trust for local modules.

**Comment by juliangruber** [comment]
I actually don't think this should live in the SDK then, as it's more stateful and the consumer code / applications need to interact with the files anyway

**Comment by juliangruber** [comment]
> we've already agreed that "date modified" is a concept we only trust for local modules.

clarification: we will only _have_ it for local modules, it's not a question of trust

**Comment by juliangruber** [comment]
To get the last modified time of a local module, we need to check the modified time of every file in its folder, and then select the newest one. This means we do need to do file watching, and check every file when the app starts (as they could have been modified while the app wasn't running).

If we keep this logic strictly in the sdk (although it is for ordering in an application, which imo isn't the sdk's business), then the sdk needs to

- during `.ready()` or when first reading a module's data, scan the mtimes of all module files
- expose mtimes, probably as `module.metadata.mtime`?
- if a file is modified while the process is running, update its internal mtime cache and emit an event, so the app can update

@dpaez I'm curious what you think about this

**Comment by dpaez** [comment]
This is interesting. Currently we are storing the last modified time under the `metadata.lastModified` property. But this is done for the `dat.json` mainly. If we proceed with this for all the files, then I should follow a strategy similar to what @juliangruber describes, I'd only change the check on `ready` to be done only when queried maybe, sort of making things _lazy_. But that's just a thought.

**Comment by dpaez** [comment]
actually now I remember that we are tracking the `lastModified` on profile and content too. But there is no check on ready (to see if anything have changed from last time. I'm wondering how does this task would look like with a daemon.

**Comment by jameslibscie** [comment]
As any file change triggers a new version (at the moment), is there a "creation date" per version in the DB? Or is that the `metadata.lastModified` you're talking about? Because then we could use that, rather than scanning all the files.

**Comment by dpaez** [comment]
There is no `creation date` field, only the `lastModified`. I think that we could use that for now.

**Comment by jameslibscie** [comment]
@juliangruber Given what @dpaez has said, do you think the SDK currently has enough to make a content list sorted by date modified and to display date modified on owned modules?

**Comment by juliangruber** [comment]
@dpaez if when you launch the process it scans all the files, then detects any changes, then bumps its version, then updates its internal `lastModified`, that indeed should be enough :)

**Comment by jameslibscie** [comment]
@dpaez You can close this issue if what @juliangruber says is indeed what happens :)
