### ISSUE TITLE
trim whitespaces in title

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/sdk-js#146]
**Describe the bug**

~According to https://github.com/p2pcommons/specs/issues/28. Currently the SDK accepts a `" "` as a valid title.~

This has changed to only address the differences/updates on the specs.
 
**To Reproduce**
~Create a module with title = `"' '"`~

**Expected behavior**
~empty title should throw an error~

**Comment by chartgerink** [comment]
Closed after discussing with @dpaez and testing in Hypergraph.
