### ISSUE TITLE
Complete metadata validation + atomic metadata validation

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#154]
**User stories**
As a developer of a p2pcommons implementation
I want to be able to validate the current metadata (`dat.json`)
so that I can protect users against errors, even those created outside my application
and
I want to be able to validate user input (possible future metadata or snippets of metadata)
so that I don't have to implement validation methods in my application that may become out of sync with the SDK's validations

**Acceptance criteria**

- [x] There is a validation method that fully validates a set of metadata that is passed to it
  - [x] Context-specific validations are possible (for example, validation on `publish` should validate that the `main` file exists)
- [x] Each part of the metadata can be validated separately, to ensure that implementations can "test" specific changes before effecting them
- [x] Make sure tests check for specific errors

**Suggested implementation**

I discussed this with @juliangruber and it seems most user/dev-friendly to us to implement all the validation methods with the same two params, namely an object containing module metadata (`dat.json`) and an object containing additional metadata like `version`, `lastModified`, `isWritable`. This allows for context-specific validation where necessary.

For a simple validation, like `title`, where the validation is not context-dependent, passing `{ title: "Nice title" }` as metadata is enough and the param for additional metadata is ignored, but passing a full (current or "hypothetical") object with metadata also works. Each method only validates what is necessary to determine whether that part of the validation is successful. Altogether, all the partial methods make up a full validation of the module metadata.

**Suggested list of validations + error messages**

This list should be up to spec with module spec `0.3.2`

*Note: it might be valuable to add error codes to each validation as well. What do you think @juliangruber? I've quickly added suggestions*

`title`

- [x] Required. "Title is required", `title_required`
- [x] Type string. "Title must be a string", `title_type`
- [x] Between 1 and 300 characters long. "Title must be between 1 and 300 characters long", `title_length`
- [x] Does not consist of only whitespace. "Title may not consist of only whitespace", `title_whitespace`

`description`

- [x] Required. "Description is required", `description_required`
- [x] Type string. "Description must be a string", `description_type`

`url`

- [x] Required. "URL is required", `url_required`
- [x] Type string. "URL must be a string", `url_type`
- [x] Starts with `hyper://`. "URL must start with hyper:// protocol", `url_protocol`
- [x] Follows regex [`^(hyper:\/\/)(\w{64})$`](https://regex101.com/r/naEFVg/5). "URL must contain non-versioned Hyperdrive key", `url_invalidkey`
- [x] The key in the URL is equal to the module's Hyperdrive key. "URL must refer to the module's own Hyperdrive key", `url_incorrectkey`

`links`

- [x] Required. "Links object is required", `links_required`
- [x] Type object. "Links must be an object", `links_type`
- [x] All keys must be strings. "Links must be an object with string keys", `links_stringkeys`
- [x] All values must be arrays. "Links must be an object with array values", `links_arrayvalues`

`links.license`

- [x] Required. "License link is required", `links_license_required`
- [x] Type array. "License must be an array", `links_license_type`
- [x] Must contain one object. "License must contain one object", `links_license_type`
  - [x] This object must contain an `href` key. "License object must have an href key", `links_license_href`
  - [x] The `href` value must be equal to `https://creativecommons.org/publicdomain/zero/1.0/legalcode`. "License link must be equal to 'https://creativecommons.org/publicdomain/zero/1.0/legalcode'", `links_license_value`

`links.spec`

- [x] Required. "Spec link is required", `links_spec_required`
- [x] Type array. "Spec must be an array", `links_spec_type`
- [x] Must contain one object. "Spec must contain one object", `links_spec_type`
  - [x] This object must contain an `href` key. "Spec object must have an href key", `links_spec_href`
  - [x] The `href` value must be a valid URL. "Spec href must refer to a valid URL", `links_spec_validurl`

`p2pcommons`

- [x] Required. "p2pcommons object is required", `p2pcommons_required`
- [x] Type object. "p2pcommons must be an object", `p2pcommons_type`

`p2pcommons.type`

- [x] Required. "p2pcommons type is required", `p2pcommons_type_required`
- [x] Type string. "p2pcommons type must be an array", `p2pcommons_type_type`
- [x] Must be equal to `profile` or `content`. "p2pcommons type must be equal to 'profile' or 'content'", `p2pcommons_type_value`

`p2pcommons.subtype`

- [x] Required. "p2pcommons subtype is required", `p2pcommons_subtype_required`
- [x] Type string. "p2pcommons subtype must be a string", `p2pcommons_subtype_type`
- [x] Follows regex [`^\w*$`](https://regex101.com/r/hDRGfc/2). "p2pcommons subtype may only include standard alphanumeric characters", `p2pcommons_subtype_alphanumeric`

`p2pcommons.main`

- [x] Required. "p2pcommons main is required", `p2pcommons_main_required`
- [x] Type string. "p2pcommons main must be a string", `p2pcommons_main_type`
- [x] Must not refer to a `.dotfile`. "p2pcommons main may not be a .dotfile", `p2pcommons_main_dotfile`
- [x] Must be a relative path to a file within the Hyperdrive OR empty (regex [`^((?!\/)|(\.\/))(?!~|\.).*(?<!\/)$`](https://regex101.com/r/MZXJnK/1)). "p2pcommons main must be a relative path to a file within the Hyperdrive OR empty", `p2pcommons_main_relativepath` *Note: this regex also excludes some `.dotfiles`, but not all, so apply after the dotfile check*
- [x] Upon publishing, must refer to an existing file. "p2pcommons main file does not exist", `p2pcommons_main_filemissing`

*Note: Perhaps this validation should be split into 2 methods, something like `validateMainFormat()` and `validateMainExists()` or `validateMain()` and `validateMainFile()`*

`p2pcommons.avatar`

- [x] May only exist if content type is `profile`. "p2pcommons avatar may only exist for profiles", `p2pcommons_avatar_moduletype`
- [x] Type string. "p2pcommons avatar must be a string", `p2pcommons_avatar_type`
- [x] Must be a relative path to a file within the Hyperdrive OR empty (regex [`^((?!\/)|(\.\/))(?!~|\.).*(?<!\/)$`](https://regex101.com/r/MZXJnK/1)). "p2pcommons avatar must be a relative path to a file within the Hyperdrive OR empty", `p2pcommons_avatar_relativepath` *Note: this regex also excludes some `.dotfiles`, which are allowed for the avatar*

`p2pcommons.authors`

- [x] Required if content type is `content`. "p2pcommons authors is required for content", `p2pcommons_authors_required`
- [x] May only exist if content type is `content`. "p2pcommons authors may only exist for content", `p2pcommons_authors_moduletype`
- [x] Type array. "p2pcommons authors must be an array", `p2pcommons_authors_type`
- [x] Each item must be a string. "p2pcommons authors must be an array of strings", `p2pcommons_authors_type`
- [x] Must contain unique values. "p2pcommons authors must be unique", `p2pcommons_authors_unique`
- [x] Each item must be a non-versioned Hyperdrive key (regex [`^(\w{64})$`](https://regex101.com/r/GQOim5/2)). "p2pcommons authors may only contain non-versioned Hyperdrive keys", `p2pcommons_authors_invalidkey`

`p2pcommons.parents`

- [x] Required if content type is `content`. "p2pcommons parents is required for content", `p2pcommons_parents_required`
- [x] May only exist if content type is `content`. "p2pcommons parents may only exist for content", `p2pcommons_parents_moduletype`
- [x] Type array. "p2pcommons parents must be an array", `p2pcommons_parents_type`
- [x] Each item must be a string. "p2pcommons parents must be an array of strings", `p2pcommons_parents_type`
- [x] Must contain unique values. "p2pcommons parents must be unique", `p2pcommons_parents_unique`
- [x] Each item must be a versioned Hyperdrive key (regex [`^(\w{64})(\+\d+)$`](https://regex101.com/r/GQOim5/3)). "p2pcommons parents may only contain versioned Hyperdrive keys", `p2pcommons_parents_invalidkey`
- [x] If an item refers to the module's own Hyperdrive key, it must refer to a preceding version. "p2pcommons parents may not refer to current or future versions of itself", `p2pcommons_parents_selfreference` *Note: it IS allowed to refer to a current version -before- updating the version number, as when the update is performed, the proposed parent and the current version number will no longer align. After the new version is created, version > parent version*
- [x] Upon setting `parents` (but not at other times), it must refer to a content module that is published by at least one of its listed authors. "p2pcommons parents must be published", `p2pcommons_parents_notpublished`

`p2pcommons.follows`

- [x] Required if content type is `profile`. "p2pcommons follows is required for profiles", `p2pcommons_follows_required`
- [x] May only exist if content type is `profile`. "p2pcommons follows may only exist for profiles", `p2pcommons_follows_moduletype`
- [x] Type array. "p2pcommons follows must be an array", `p2pcommons_follows_type`
- [x] Each item must be a string. "p2pcommons follows must be an array of strings", `p2pcommons_follows_type`
- [x] Must contain unique values. "p2pcommons follows must be unique", `p2pcommons_follows_unique`
- [x] Each item must be a versioned OR non-versioned Hyperdrive key (regex [`^(\w{64})(\+\d+)?$`](https://regex101.com/r/GQOim5/4)). "p2pcommons follows may only contain Hyperdrive keys (versioned or non-versioned)", `p2pcommons_follows_invalidkey`
- [x] An item may not refer to the module's own Hyperdrive key at any version. "p2pcommons follows may not contain the profile's own Hyperdrive key", `p2pcommons_follows_selfreference`

`p2pcommons.contents`

- [x] Required if content type is `profile`. "p2pcommons contents is required for profiles", `p2pcommons_contents_required`
- [x] May only exist if content type is `profile`. "p2pcommons contents may only exist for profiles", `p2pcommons_contents_moduletype`
- [x] Type array. "p2pcommons contents must be an array", `p2pcommons_contents_type`
- [x] Each item must be a string. "p2pcommons contents must be an array of strings", `p2pcommons_contents_type`
- [x] Must contain unique values. "p2pcommons contents must be unique", `p2pcommons_contents_unique`
- [x] Each item must be a versioned OR non-versioned Hyperdrive key (regex [`^(\w{64})(\+\d+)?$`](https://regex101.com/r/GQOim5/4)). "p2pcommons contents may only contain Hyperdrive keys (versioned or non-versioned)", `p2pcommons_contents_invalidkey`

**Comment by chartgerink** [comment]
> Must be a relative path to a file within the Hyperdrive OR empty

`p2pcommons.main` is not allowed to be empty, AFAIK? This is straight from the spec:

>MUST be a string containing one relative path

I interpret this as 1 and only 1 relative path, not zero paths. As such, the module spec doesn't indicate that it may be empty. 

I also notice that we do not set `main` for profiles. For profiles, we could default to itself `./` because we don't provide a way to set a main yet. This would mean the regex needs to be updated to as well [`^((?!\/)|(\.\/))(?!~|\.).?.*(?<!\/)?$`](https://regex101.com/r/H4p4VF/1)

**Comment by jameslibscie** [comment]
> > Must be a relative path to a file within the Hyperdrive OR empty
> 
> `p2pcommons.main` is not allowed to be empty, AFAIK? This is straight from the spec:
> 
> > MUST be a string containing one relative path
> 
> I interpret this as 1 and only 1 relative path, not zero paths. As such, the module spec doesn't indicate that it may be empty.
> 
> I also notice that we do not set `main` for profiles. For profiles, we could default to itself `./` because we don't provide a way to set a main yet. This would mean the regex needs to be updated to as well [`^((?!\/)|(\.\/))(?!~|\.).?.*(?<!\/)?$`](https://regex101.com/r/H4p4VF/1)

You're correct on the validation for content versus the specs, but there's a reason why the validation is set up this way. Having `main` be required directly after creation would be problematic, as it doesn't allow users the chance to add files and select a main file. We validate that the main file is filled and refers to an existing file upon registration instead. Perhaps a spec change to indicate that `main` is only required upon registration would be good? (I have some other minor changes that I'm discovering through this process that I'll propose later).

Good catch on the profiles though. Technically this won't be caught by the current setup as `validate()` currently allows `main` to be empty and `validateOnRegister()` wouldn't be called for profiles. But that's very implicit and the SDK should reflect the specs. Perhaps we should make `main` optional for profiles for now?

**Comment by chartgerink** [comment]
Sound like good propositions! I didn't realise this was an interim validation too, I thought it was only final validation. If you're making proposals for the specs, could you include the optional `main` for profiles as well?
