### ISSUE TITLE
improve test coverage

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#155]
Hey Diego 👋,

As discussed in our office hour, we would like to increase the test coverage on the sdk, as often issues are found in the CLI when updating to a new sdk version.

We mentioned a couple potential strategies:

- a certain test coverage percentage
- regression tests
- test that the sdk is spec compliant
- integration tests

**Comment by jameslibscie** [comment]
See also #154 for bringing the SDK up to spec and creating the validations that can then be fully tested.

**Comment by jameslibscie** [comment]
Closed via #167
