### ISSUE TITLE
Read-only registered modules

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#172]
**Is your feature request related to a problem? Please describe.**
Registered content is supposed to be immutable. I can now still edit it on my local version.

**Describe the solution you'd like**
To prevent people from messing around with registered content on their local device, it helps to lock versioned folders to read-only by default.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by juliangruber** [comment]
> To prevent people from messing around with registered content on their local device, it helps to lock versioned folders to read-only by default.

This seems to fix just a small part of the problem. People might want to edit further and publish new versions, so they will need a working directory. I actually don't understand why it's bad to be able to edit files after registering a module - I know what I registered and that my edits coming afterwards aren't part of it. Maybe we instead want a way to view the already registered version's file contents?

**Comment by juliangruber** [comment]
> Registered content is supposed to be immutable. I can now still edit it on my local version.

You aren't mutating your registered content, when you do that you bump the version automatically.

**Comment by chartgerink** [comment]
This is a local precaution (that can be circumvented of course); it indeed doesn't change what's on the p2pcommons. Because we store versioned and unversioned copies of the hyperdrives, I think this is important (we don't use checkout AFAIK?).

Here are a few scenario's to try and clarify what I mean.

# Scenario 1: my own registered content

I register my content from `hyper://456` and have `~/Hyperdrive/p2pcommons/456` (my working directory). 

I register at version 6, I get `~/Hyperdrive/p2pcommons/456+6` as well. 

The module contains `test.txt`. I should be able to edit it in the working directory (unversioned) and create new registrations with that. 

The versioned directory tries to stay at the same version, because changes makes it inconsistent with the actual registration version.

If I would make edits in the versioned folder, what I see when I view my registration can be different from when you clone my registration. It is also easy to forget what the content looked like when you registered if it was a while ago or you have many registrations. 

# Scenario 2

I clone somebody else's registration from `hyper://599+2`, which gives me the versioned folder `~/Hyperdrive/p2pcommons/599+2`. I do not have write access to `hyper://599`.

If I would like to work with the files in the registration, I can create my own module that contains the registration's files. E.g., `hyper://599+2` --> `hyper://632`. I now have a working directory (with `599+2` as a parent) to continue the work.

If I would be able to edit `599+2`, I would have a different local file from the actual registration.

**Comment by juliangruber** [comment]
> The versioned directory tries to stay at the same version, because changes makes it inconsistent with the actual registration version.
> 
> If I would make edits in the versioned folder, what I see when I view my registration can be different from when you clone my registration. It is also easy to forget what the content looked like when you registered if it was a while ago or you have many registrations.

Thank you for explaining, I understand now. I didn't know we stored a versioned copy of the module folder. We should be able to create read-only files through node's fs module (which also works on Windows) :+1:.

**Comment by chartgerink** [comment]
@dpaez and I chatted during the office hour today and he made some valid points:

1. Unversioned modules need to still be written to, so making them read-only will throw issues upon update.
2. Versioned modules can always be made read only without issues.

We consider these separate implementations and will go ahead with 2. only for now and 1. at a later timepoint after consulting also with @juliangruber.
