### ISSUE TITLE
EBUSY error still can't be caught properly

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#184]
https://github.com/p2pcommons/sdk-js/blob/fcd6c55a9d1ebb6da1ac485d730acde7f873c51e/index.js#L632-L636

In the `init()` method, throwing an error inside an event handler will not make it catchable. Since the event listener gets called outside of the async function's execution flow, it won't make the function throw but rather only be catchable on `process.on('uncaughtException', fn)`.

We might not even want to throw this error, since in the case we've been seeing it can be ignored, so we wouldn't want to abort the flow of the `init()` function. I'm not sure how to expose this error properly, as it's more of a warning. Maybe `sdk.on('warn', fn)`?

**Comment by dpaez** [comment]
Oh! We focused too much on the error itself and missed this. We can emit a warning. 

Would you like to see any specific message?

**Comment by juliangruber** [comment]
> Would you like to see any specific message?

The message doesn't matter as long as it has a `.code = 'EBUSY'`
