### ISSUE TITLE
Inconsistent data is returned from .get()

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#195]
1. Have a module, with say `version=58, main=README.md`
2. Call `await p2p.set({ url, main: 'CONTRIBUTING.md })`
3. Call `await p2p.get(url)`, returns `version=58, main=CONTRIBUTING.md`, instead of `version=59, main=CONTRIBUTING.md

This leads to rendering inconsistencies in Hypergraph, discovered in https://github.com/hypergraph-xyz/desktop/issues/69

**Comment by dpaez** [comment]
This should have been closed with #197. We can re-open if it happens again.
