### ISSUE TITLE
Deregister removes first registration when a non-registered key is provided

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#196]
## Description

I have multiple versioned content modules registered to my profile. When I deregister one of them, one of the other contents is removed from my profile.
I *think* this is caused by:
1. `get()` / `clone()` returns the wrong version for the module I'm trying to deregister - a different version than the one on my profile
2. `deregister()` doesn't check whether the key is actually included in the profile's contents. `indexOf` returns -1, so the `0th` element gets spliced off?

## To Reproduce

1. Create several content modules
2. Register them to your profile
3. Make changes to one of them outside of the SDK (by adding files to the unversioned folder for example)
4. Deregister the modules
5. Register the modules at their latest versions
6. Deregister the module you've updated

## Expected behavior

The updated module is deregistered.

## Actual behavior

A different module is deregistered.

## Screenshots

I have a recording of this happening in Hypergraph.

## System

- OS (incl. version): Windows 10
- SDK version: Hypergraph 0.4.0 / SDK 0.6.3

**Comment by dpaez** [comment]
Good catch James, we can register a few more modules in the [deregister test](https://github.com/p2pcommons/sdk-js/blob/main/tests/index.js#L1273) to see how it breaks and fix from there.
