### ISSUE TITLE
more usable validation errors

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#21]
Currently I'm running custom validations in the hypergraph cli in order to detect

- updates to metadata not allowed, eg when setting an unknown key
- validation errors, eg when setting an empty title

The code looks somewhat like this:

```js
const set = async (metadata) {
  const current = await p2p.get(metadata.url)
  const allowedKeys = ['title', 'description', 'main']

  for (const key of Object.keys(metadata)) {
    if (metadata[key] !== current[key]) {
      if (!allowedKeys.includes(key)) {
        throw new this.InvalidKeyError(
          `Only allowed to update keys ${allowedKeys.join(', ')}`
        )
      } else if (validate[key]) {
        const result = validate[key](metadata[key])
        if (typeof result === 'string') {
          throw new this.ValidationError(result)
        }
      }
    }
  }

  return p2p.set(metadata)
 }
```

The important part here is that it's thrown a `InvalidKeyError` or `ValidationError`, which are custom error classes. These can then be checked by the cli layer in order to print the proper error message.

The SDK is currently only using `assert`, which doesn't respond with a custom error class. What do you think about introducing such?

The error setup in the cli is currently:

```js
class UserError extends Error {}
class InvalidKeyError extends UserError {}
class ValidationError extends UserError {}
```

If the SDK exports something like this, that would be possible:

```js
const P2PCommons = require('@p2pcommons/sdk-js')

try {
  await p2p.set(object)
} catch (err) {
  if (err instanceof P2PCommons.ValidationError) {
    console.log('oh noes', err.message)
  }
}
```

What do you think?

**Comment by dpaez** [comment]
Cool, yes. I was thinking about this, having better errors (a bit more structured maybe). `assert` is super nice but a bit short. Anyway it helps me get here. So, I think we can add this change and export the new errors.

As you suggest we can start by adding: 
- invalid keys
- validation errors

**Comment by juliangruber** [comment]
Nice! I'm actually not sure whether it's better to do instance of checks or simply attach some known properties to errors, but since we control the code here instance of checks should be nicer DX
