### ISSUE TITLE
Hyperspace replacing hyperdrive-daemon

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#214]
During the recent Dat conference, mafintosh gave a talk on the "State of Hyper". Specifically, the interesting bit [starts here](https://youtu.be/Cm9fwxnXg9k?t=1081). 

The talk announces that the [`hyperdrive-daemon`](https://github.com/hypercore-protocol/hyperdrive-daemon) will be replaced by [`hyperspace`](https://github.com/hyperspace-org) (the next iteration of the daemon). The FUSE support will live in [@hyperspace/hyperdrive-service](https://github.com/hyperspace-org/hyperdrive-service) I think. 

The core reasoning is that the `hyperdrive-daemon` is focused purely on Hyperdrives, but there are many `hypercore` data structures that need replicating. `hyperspace` is a daemon that aims to do that, but is currently experimental. This means that it can use `hypertrie` and other structures more easily too in the future.

Knowing this, @dpaez and I discussed a bit about what to do. A lot of work by @dpaez has already been done on integrating the `hyperdrive-daemon`, and `hyperspace` does provide [a migration tool](https://github.com/hyperspace-org/migration-tool). 

PR #160 would need (considerable) rebasing with `main` by now, plus networking is functional already. For now, we regard #160 stale and revisit this work in a few months, as `hyperspace` (potentially) stabilises. We can still use the lessons learned from it when the next integration comes around.

What do you think?

# Affected issues / PRs

#122, #125, #160, the `hyperdaemon` app.

![](https://media.giphy.com/media/LwhhZsEHFQgSs/giphy.gif)

**Comment by dpaez** [comment]
Thanks for the summary and explanation Chris. I agree with this plan.

**Comment by chartgerink** [comment]
Closing this as it was a discussion item that is no longer active.
