### ISSUE TITLE
unable to set subtype

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#22]
Currently when setting `{ type: 'content', subtype: 'Theory' }` in `p2p.init()`, the subtype comes out as `content` in the dat.json.

This is required for https://github.com/hypergraph-xyz/cli/issues/20.

**Comment by dpaez** [comment]
Currently, the `init` method only accepts `type`, `title` and `description` params. Description is the only field that can be blank. Other `dat.json` values are set to a default initial value. This behaviour was based on the original code. I double check the modules spec on the [initialization section](https://github.com/p2pcommons/specs/blob/master/module.md#initialization) but it does not specify any default params. 

I'm going to add the `subtype` and maybe we can update the modules spec too adding this information. :+1:
