### ISSUE TITLE
listContents() doesn't reliably return latest version

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#220]
> Using some `console.log`s, I noticed that the same module is returned with different versions in two consecutive `p2p.listContents()` calls:
> 
> First call, where it's listed as draft (`version = 11`)
> 
> ![image](https://user-images.githubusercontent.com/10247/90646441-80311380-e237-11ea-8a85-58a6b19fd2c5.png)
> 
> Second call, where it isn't (`version = 4`)
> 
> ![image](https://user-images.githubusercontent.com/10247/90646459-8626f480-e237-11ea-8680-409aab8491d0.png)

This causes modules to display twice in Hypergraph, for example 1 draft version and 1 registered version.

**Comment by dpaez** [comment]
I think that somehow we entered wrong/bad data to the localdb to reach a case like the one described in the issue. 

We can add some checks on `listContent` method to filter values and return the one with the latest modified time or latest version. But which one? It should be the same.

On the other hand, p2pcommons/sdk-js#221 is an attempt to prevent this.

**Comment by jameslibscie** [comment]
Should be fixed with #221
