### ISSUE TITLE
delete: all versions

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/sdk-js#226]
**Is your feature request related to a problem? Please describe.**
delete a registered module. When we delete a registered module and we pass the **unversioned** url, the `delete` method only deletes the **unversioned** folder. But, the profile contents is pointing to the **versioned** url. This can led to confusion.

**Describe the solution you'd like**
`delete` method could destroy all the versions that exists in the directory related to the unversioned key. This would only happen if the delete method receives an unversioned key and the force delete param is `true`. This would also trigger as many `deregister` calls as versions found to avoid inconsistencies. 

**Describe alternatives you've considered**
A simple alternative is to pass the specific version on delete. **This is particularly important if we want to remove content from a profile.** 

**Additional context**
We can also make use of a new parameter passed to `delete`, something like `deleteAll`. Or it can be a new method `deleteAll`.

**Comment by chartgerink** [comment]
Seems to be fixed.
