### ISSUE TITLE
False positives on main file extension check

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#231]
The main file extension check currently disallows `.js` files. Since there are likely many plain text file types that are not on the list, it might be wise to implement a plain text checker, like:

[https://www.npmjs.com/package/istextorbinary](https://www.npmjs.com/package/istextorbinary)
[https://www.npmjs.com/package/isbinaryfile](https://www.npmjs.com/package/isbinaryfile)
[https://www.npmjs.com/package/chardet](https://www.npmjs.com/package/chardet)

See also: https://www.notion.so/File-spec-validation-plan-a059300d54c546199b6e08f75b542a2f

**Comment by dpaez** [comment]
Closed with #233
