### ISSUE TITLE
Delete tries to deregister from remote profile

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#232]
## Description

When deleting a content module that is has local _and_ remote authors, and it has been registered to the local author, the SDK will also try to deregister it from the remote author, whose profile is not writable.

## To Reproduce

1. Init local profile
2. Init remote profile
3. Follow remote profile
4. Init content module with both as authors
5. Register content module to local profile
6. Delete content module

## Expected behavior

The content module is removed from the local profile but the remote profile stays untouched.

## Actual behavior

The SDK tries to remove the content module from the remote profile and throws an error that the profile is unwritable.

## Additional context

Even if the remote profile has the content module registered, it wouldn't be writable, so delete shouldn't try to modify it.

**Comment by jameslibscie** [comment]
Does this bug occur in #227?

**Comment by juliangruber** [comment]
> Does this bug occur in #227?

Yes, iirc we discovered this bug testing that branch.

**Comment by dpaez** [comment]
👍 Going to add the fix to #227
