### ISSUE TITLE
Unfollow doesn't remove contents from db

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#241]
## Description

When I unfollow someone, the database still contains all their work. I expect only the work from people that I follow in the database. Or a way to filter on those who I follow

## Expected behavior

The database is up to date with the latest contents from the people I follow.

## Actual behavior

The database is up to date with the latest contents from the people I followed or follow.

## Additional context

This issue came up for the first time in [this PR for Hypergraph](https://github.com/hypergraph-xyz/desktop/pull/263#pullrequestreview-485900397).

If there are multiple authors, and I follow multiple authors, I would want the content to remain in the db for the other authors even after unfollowing one author.

**Comment by jameslibscie** [comment]
What about (shared) content you view from authors you don't follow? Should that be auto-cleaned from the database?
And content that is removed from authors' profiles?

**Comment by juliangruber** [comment]
> What about (shared) content you view from authors you don't follow?

Good point, in order to view files this kind of module also needed to be downloaded and thus is in the db.

**Comment by chartgerink** [comment]
Hm yes. We might need to add a variable that we could filter on for the feed? As in, we don't remove it from the db, but we can remove it from the feed.

**Comment by juliangruber** [comment]
The feed shouldn't be the problem here, as it only lists content modules from people you explicitly follow. You discovered this in the authors dropdown however, where we expose all profiles known to the db. I'm not sure following someone is a _good_ requirement for being able to add them as author, but it's unlikely you wouldn't follow a co-author.

**Comment by chartgerink** [comment]
Oh it was never my intention indeed to not allow people you don't follow to not be co-authors. Pardon the miscommunication.

I saw content shared by people I used to follow, but no longer, in my feed, so that was exactly the problem on my end.

**Comment by juliangruber** [comment]
Interesting, maybe it didn't refresh the feed.

The current logic is this:

https://github.com/hypergraph-xyz/desktop/blob/94f00c3fc586d327bdb3dff434fd65a1cd29e510/app/components/feed/feed.js#L16-L29

For your and every profile you follow, list all their listed modules.

I don't think this is an SDK bug then. If you can still reproduce, could you please open an issue with steps on Hypergraph Desktop?

**Comment by chartgerink** [comment]
Ah okay! 

Couldn't reproduce anymore so closing this issue 😅
