### ISSUE TITLE
Change release procedure to `np`

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#263]
In order to harmonize release procedures, it is worthwhile to switch to [`np`](https://github.com/sindresorhus/np) for the release pipeline.

**Comment by dpaez** [comment]
We can have a new `release` script in the `package.json` that calls `np`. Also we will need to install np as a dev dep.

Lastly, we will need to update the release section in the docs. Something similar to what [hypergraph-xyz/cli](https://github.com/hypergraph-xyz/cli#how-to-release) has would work here too.
