### ISSUE TITLE
expose constructor

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#3]
It was unexpected for me to instantiate

```js
const p2p = P2PCommons()
```

instead of

```js
const p2p = new P2PCommons()
```

which is the default with es6 classes. I don't feel strongly about this but just wanted to share this was surprising to me.

**Comment by dpaez** [comment]
yup, will change that, I was following the style of hyperdrive and similar modules.

**Comment by dpaez** [comment]
Closed with latest release #4
