### ISSUE TITLE
unable to update profile module

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#41]
Given a `profile` module and sdk `v0.3.0`, this fails:

```js
await p2p.set({
  url: '7cc2f007a10bdd9c6355428642524c7cf19a331a5ed0c0408582ed478b141d69',
  title: 'name',
  description: 'desc'
})

// throws
// Invalid <RecordType>
```

**Comment by juliangruber** [comment]
With a `content` module everything works just fine

**Comment by dpaez** [comment]
Will look into it!

**Comment by dpaez** [comment]
Hi @juliangruber I made some updates to the `set` test, now we are updating a profile module too, but tests are passing. Is this a similar scenario to yours?

**Comment by juliangruber** [comment]
Yes thank you, the bug was on my side 🙏
