### ISSUE TITLE
expose key in `ValidationError`

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#45]
inspecting a `ValidationError` thrown, it's only possible to deduct the violating key by searching in the string `err.args[1]`. It would be handy if there was an extra prop on the error exposing just the key.

**Comment by dpaez** [comment]
Like a new property? E.g.: `err.received` containing the received value? 
If that is the case, I guess we should also add the `err.expected` with the expected value

**Comment by juliangruber** [comment]
that sounds great, but we also `err.key`, otherwise we still have to do string parsing to figure out which property conflicted

**Comment by dpaez** [comment]
cool, yeah I've figured out that too.
