### ISSUE TITLE
Registered content does not produce versioned Dat key

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#48]
Upon implementation of the `sdk-js@v0.3.0` in the [`@hypergraph-xyz/cli`](https://github.com/hypergraph-xyz/cli/pull/56), the discussion went towards the Dat keys that are registered to a profile.

The registered content module Dat key is not versioned at the moment (i.e., `<hash>` instead of `<hash>+<version>`). The module specification outlines that this [should be versioned](https://github.com/p2pcommons/specs/blob/master/module.md#keyvalues).

As a sidenote: The spec allows for non-versioned links in the `contents` key, which is a separate function specified as public drafts. This we don't have on the roadmap at the moment.

**Comment by dpaez** [comment]
Working on this for the last days. While I was trying to add some tests for this use case I found that the checkouts are not working as expected (some versions return data while others not). Currently I'm trying to create a small case to see if the error comes from latest hyperdrive or if it is solely in our codebase.
