### ISSUE TITLE
Delete module

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#62]
**User story**
As a user of a p2pcommons implementation
I want to be able to delete my own created content modules
so that I can correct mistakes and keep my projects organised

**Acceptance criteria**
- Delete is only possible for modules the user has write access to
- Delete only deletes the module locally and has no effect on remote copies
- The ability to delete profile modules will probably be necessary at some point, but is not top priority now. Can be included if it's little extra work.

**Comment by dpaez** [comment]
Closed with #69
