### ISSUE TITLE
New method: unpublish content

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/sdk-js#73]
**User story**
As a user of a p2pcommons implementation
I want to remove content from my profile
so that I can correct mistakes and keep my profile organised

**Acceptance criteria**
- The user can remove content from their own profile in a way that ensures that profile and content modules remain valid

**Possible implementations**
_Unpublish_ would be like the opposite action of current register method

So the API could be like `unpublish(contentKey, profileKey)` ? This means that the user already known the content and profile.

Another option is `unpublish(contentKey)`. This would remove the content from all the `contents` field of all the profiles.

**Comment by jameslibscie** [comment]
@dpaez  The `unpublish(contentKey, profileKey)` sounds easier, right? I think the user would always know their own profile, so I think this sounds like the best first implementation. If we need removal from all profiles, we can expand the method later or add search methods.

**Comment by dpaez** [comment]
@jameslibscie yeah, it becomes a bit easier since it has more context, preconditions (eg: only deleting content from *my profile*, etc). Working on this now.

**Comment by chartgerink** [comment]
Sounds like the only way to go too, especially once there are people co-authoring content they don't necessarily own (given that we haven't implemented hypertrie, I think?).

Maybe we could think about redubbing the `register()` to `publish()` as well? Would make for more consistency? If so, probably a separate issue.

https://github.com/p2pcommons/sdk-js/blob/master/index.js#L860

**Comment by juliangruber** [comment]
> Maybe we could think about redubbing the `register()` to `publish()` as well? Would make for more consistency? If so, probably a separate issue.

Yes please

**Comment by dpaez** [comment]
> Maybe we could think about redubbing the register() to publish() as well? Would make for more consistency? If so, probably a separate issue.

Oh I'll also rename it 👍
