### ISSUE TITLE
Follow & unfollow profile

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#75]
**User story**
As a user of a p2pcommons implementation
I want to be able to follow a profile
so that the implementation I'm using can help me stay up to date with that person's content

**Acceptance criteria**
- `p2pcommons.follows` metadata can be manipulated by the module's owner by adding or removing valid Dat archive keys (see [specs](https://github.com/p2pcommons/specs/blob/master/module.md#keyvalues))
- `p2pcommons.follows` may only be manipulated on profile modules
- `p2pcommons.follows` may only refer to profile modules
- `p2pcommons.follows` may be versioned

**Comment by dpaez** [comment]
Besides modify follows metadata, should we do something with the profile that one user follows. I'm thinking about this line:

> so that the implementation I'm using can help me stay up to date with that person's content

e.g: should we download some content?

**Comment by chartgerink** [comment]
I think the expected behavior ultimately would be that the localdb also updates with the content from that profile, yes. We would need (have?) an index method to do this generically for a module, given that this would also apply for the content.

**Comment by jameslibscie** [comment]
I'd say for now updating the metadata is enough, so this can be closed upon merge. I'm going to plan a session regarding Hypergraph networking features very soon (that will lead to our projected v1 feature list). In this session we can also discuss what features belong where (SDK vs implementation) and this will lead to new issues for the SDK.

Maybe this is very obvious to you in this case, but I can imagine collecting and managing followed profile data might be something the implementation handles? Is "implementation" the right word to use in this case btw? Don't need an answer for this now, but this is something that we can discuss then :)

**Comment by chartgerink** [comment]
> I'd say for now updating the metadata is enough, so this can be closed upon merge. I'm going to plan a session regarding Hypergraph networking features very soon (that will lead to our projected v1 feature list). In this session we can also discuss what features belong where (SDK vs implementation) and this will lead to new issues for the SDK.
> 
> Maybe this is very obvious to you in this case, but I can imagine collecting and managing followed profile data might be something the implementation handles? Is "implementation" the right word to use in this case btw? Don't need an answer for this now, but this is something that we can discuss then :)

Anything that relates to the @p2pcommons/specs directly needs to be in the SDK, anything else can be done in the implementation. This means that for interoperability purposes, it makes sense that the SDK deals with the localdb too.
