### ISSUE TITLE
urls inconsistent

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#84]
I just noticed that the sdk writes to dat.json `parents: [encode(key)], authors: ['dat://${encode(key)}']`. I think it would be more consistent for the consumer if both either had the `dat://` prefix or neither.

**Comment by juliangruber** [comment]
Actually it seems to depend on which url the consumer passes in when creating/updating the module's parent field, so that doesn't seem to get sanitized.

**Comment by dpaez** [comment]
SDK was using the dat url regexp [defined on the spec](https://github.com/p2pcommons/specs/blob/master/module.md#keyvalues). Those made the dat prefix optional. I've changed this so it's mandatory now. 

This is a simple change that can help maintaining consistency. But I'd like to allow non prefixed keys, but that would require some refactoring. This also raise another question, some properties are modified via exclusive methods (like publishing and following) but all of them can be updated using `set`. 
Should we handle them differently?

**Comment by juliangruber** [comment]
> some properties are modified via exclusive methods (like publishing and following) but all of them can be updated using `set`.

This is an interesting observation. I guess if publishing for example in the future will contain more logic than adding a key to an array, it makes sense to have a separate method. However it seems that all of the validations could live inside `set()`, and even the sdk's `publish()` method for example could then internally use `set()`? This way `publish()` would be more of a convenience method for now. What do you think?

**Comment by dpaez** [comment]
Oh I think this should be improved with #115 (planned for release: 0.5.3)

**Comment by jameslibscie** [comment]
@dpaez Is this something that @juliangruber can close once he's upgraded to 0.5.3 and concluded that this works correctly?

**Comment by dpaez** [comment]
@jameslibscie yes

**Comment by juliangruber** [comment]
This can be closed because we're going to update the spec not to mention urls any more
