### ISSUE TITLE
Optionally delete local files belonging to content module

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#90]
**User story**
As a user of a p2pcommons implementation
I want to delete the files associated with a content module
so that I don't end up with stray files that are hard to clean up

**Acceptance criteria**
- Deleting local files is optional
- Deleting local files moves the entire Dat archive folder to Trash / Recycle Bin / OS equivalent

**Comment by juliangruber** [comment]
> * Deleting local files moves the entire Dat archive folder to Trash / Recycle Bin / OS equivalent

there are some node modules for this, i think by sindre
