### ISSUE TITLE
verify method

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/sdk-js#97]
**User story**
As an author
I want a distinction to be made between content that is verified to be mine and content that is not
so that I can have control over the work officially connected to my profile

**Acceptance criteria *(mostly from [@p2pcommons/specs/modue.md](https://github.com/p2pcommons/specs/blob/master/module.md))***
- The origin module to verify MUST be of `p2pcommons.type: content` and verification MUST occur on a specific version (i.e., versioned Dat archive key).
- The destination module in verification MUST be of `p2pcommons.type: profile` and SHOULD be the latest version (i.e., non-versioned Dat archive key). Verification MUST NOT be based on the outcome of verification across multiple versions (i.e., verification MUST be version specific).
- A version specific origin module MUST be deemed verified when all its `p2pcommons.authors` (destination) modules include the versioned origin module in their `p2pcommons.contents` property.
- The response when either or both of the modules are not available to be verified must be distinguishable from the response that occurs when a module is deemed not verified (for example by returning an error).

**Comment by jameslibscie** [comment]
@dpaez I filled in the specs. If this seems clear and complete to you, please remove the `needs spec` label.
